export const Endpoints = {
  auth: {
    login: '/login',
    logout: '/logout',
  },
  products: {
    url: '/products',
    update: '/products/:id',
    delete: '/products/:id',
    search: '/products/search',
    upload: '/upload-image',
    export: '/products/export',
    available: '/products/:id/product-items/available',
    listOptions: '/products/options',
    deleteMany: '/products/delete-many',
  },
  productItems: {
    url: '/product-items',
    search: '/devices/search',
    export: '/product-items/export',
    import: '/product-items/batch-upgrade-wifi',
  },
  productCategory: {
    url: '/product-categories',
    search: '/product-categories/search',
    deleteMany: '/product-categories/delete-many',
    delete: '/product-categories/:id',
    update: '/product-categories/:id',
    getById: '/product-categories/:id',
    getDetailById: '/product-categories/:id/detail',
    export: '/product-categories/export',
  },
  package: {
    url: '/packages',
    update: '/packages/:id',
    delete: '/packages/:id',
    search: '/packages/search',
  },
  warehouses: {
    url: '/warehouses',
    search: '/warehouses/search',
    detail: '/warehouses/:id/detail',
    delete_all: '/warehouses/delete-all',
    delete_many: '/warehouses/delete-many',
  },
  customerGroups: {
    search: '/customer-groups/search',
    create: '/customer-groups',
    deleteAll: '/customer-groups/delete-all',
    deleteMany: '/customer-groups/delete-many',
  },
  customer: {
    contact_search: '/customer-contacts/search',
    create: '/customers',
    search: '/customers/search',
    address: '/customer-addresses',
    address_search: '/customer-addresses/search',
    contact: '/customer-contacts',
    deleteAll: '/customers/delete-all',
    import: '/customers/import',
    deleteCustomerFromCustomerGroup: '/customers/customer-group',
    detail: '/customers/:id/detail',
    deleteMany: '/customers/delete-many',
    customerPriceList: '/customers/:id/price-list',
  },
  customerServices: {
    create: '/customer-services',
    getById: '/customer-services/:id',
    search: '/customer-services/search',
    deleteAll: '/customer-services/delete-all',
    deleteMany: '/customer-services/delete-many',
    listAllData: '/customer-services/list-all-data',
    import: '/customer-services/import',
    addInvoice: '/customer-services-billing',
    searchBilling: '/customer-services-billing/search',
    deleteAllBilling: '/customer-services-billing/delete-all',
    active: '/customer-services/active',
    cancel: '/customer-services/cancel/:id',
    activeWifi: '/customer-services/active-wifi',
    cancelWifi: '/customer-services/cancel-wifi',
    exchangeProductItem: '/customer-services/:id/exchange-product-item',
    availableProductItem: '/customer/:id/product-items/available',
    sendBilling: '/customer-services/send-billing',
  },
  priceRules: {
    search: '/price-lists/search',
    url: '/price-lists',
    deleteAll: '/price-lists/delete-all',
    update: '/price-lists/:id',
    delete: '/price-lists/:id',
    deleteMany: '/price-lists/delete-many',
    getById: '/price-lists/:id',
    getDetailById: '/price-lists/:id/detail',
  },
  priceRuleProduct: {
    create: '/price-list-products',
    delete: '/price-list-products/:id',
    deleteMany: '/price-list-products/delete-many',
    update: '/price-list-products/:id',
    getById: '/price-list-products/:id',
    url: '/price-list-products',
  },
  priceRulePackage: {
    create: '/price-list-packages',
    delete: '/price-list-packages/:id',
    update: '/price-list-packages/:id',
    getById: '/price-list-packages/:id',
    url: '/price-list-packages',
  },
  inventory: {
    search: 'inventories/search',
    issue: 'transaction-receipts/goods-issue',
  },
  inventoryReceipt: {
    url: 'transaction-receipts/goods-issue',
    search: 'inventory-receipts/search',
    export: 'inventory-receipts/export',
    detail: 'inventory-receipts/detail',
  },
  inventoryIssue: {
    url: 'inventory-issues',
    search: 'inventory-issues/search',
    export: 'inventory-issues/export',
    detail: 'inventory-issues/detail',
  },
  order: {
    url: '/orders',
    search: '/orders/search',
    updateStatus: '/orders/:id/update-status',
    detail: '/orders/:id',
    getQuote: '/orders/get-quote',
    search: '/orders/search',
    detailById: '/orders/:id/detail',
  },
  tag: {
    url: '/tag',
    search: '/tag/search',
    deleteAll: '/tag/delete-all',
  },
  bank: {
    url: 'bank-accounts',
  },
  return: {
    url: '/returns',
  },
  serviceOrder: {
    url: '/report/customer-service/monthly-billing',
  },
  exchange: {
    url: '/exchanges',
  },
  discount: {
    available: '/discounts/available',
  },
  payments: {
    url: '/payments',
    forOrder: '/payments/for-order',
    search: '/payments/search',
    export: '/payments/export',
    detail: '/payments/:id/detail',
  },
  transactionReceipt: {
    url: '/transaction-receipts',
    search: '/transaction-receipts/search',
    export: '/transaction-receipts/export',
    detail: '/transaction-receipts/:id/detail',
    createReceipt: '/transaction-receipts/goods-receipt',
  },
  device: {
    search: '/devices/search',
  },
  stock: {
    inventorySummary: '/stocks/inventory-summary',
    productQuantity: '/stocks/product-quantity-summary',
  },
  report: {
    revenueManagement: '/report/revenue-management',
    salesManagement: '/report/sales-management',
    productStatusManagements: '/report/product-status-management',
    returnDeviceManagement: '/report/return-device-management',
    packageManagement: '/report/package-management',
  },
} as const;
